Add calculating long wav frr again
wenet-e2e/wekws pull request #64
Opened 2022-03-23 06:40 UTC by blessyyyu

2022-03-23 06:47 UTC, robin1001 commented on kws/bin/score_longwav.py
> +                    score = ' '.join([str("%.2g" % x) for x in score.tolist()])
python str '{:.2}'.format(x);

2022-03-23 06:49 UTC, robin1001 commented on kws/bin/score_longwav.py
> +                    score = ' '.join([str("%.2g" % x) for x in score.tolist()])
score = ' '.join(['{.3f}'.format(x) for x in ...]

2022-03-23 06:50 UTC, robin1001 commented on kws/bin/compute_det_longwav.py
> +    # utt_id : score list
remove useless comment

2022-03-23 07:02 UTC, robin1001 commented on kws/bin/score_longwav.py
> +                # mask = padding_mask(lengths).unsqueeze(2)
remove it, it's useless

2022-03-23 07:02 UTC, robin1001 commented on kws/bin/score_longwav.py
> +    parser.add_argument('--score_file_dir',
write score in just one file

2022-03-23 07:04 UTC, robin1001 commented on kws/bin/compute_det_longwav.py
> +    window_shift = 50
set is as a parameter

2022-03-23 07:10 UTC, robin1001 requested changes
please see inline.

2022-03-23 10:02 UTC, robin1001 commented on examples/hi_xiaowen/s0/run.sh
> +    --num_keywords $num_keywords  \
this parameter is not required

2022-03-23 10:08 UTC, robin1001 requested changes
please see inline.

2022-03-24 03:05 UTC, robin1001 commented on kws/bin/compute_det.py
> +            score_table[key].append(scores)
1. score_table.get(key, [])
2. if key not in score_table: score_table[key] = []

2022-03-24 03:08 UTC, robin1001 commented on kws/bin/compute_det.py
> +        keyword_index = int(args.stats_file.split('/')[-1].split('.')[1])
use args.keyword

2022-03-24 03:13 UTC, robin1001 commented on kws/bin/compute_det.py
>          for line in fin:
``` python
for i, line in enumerate(fin):
    if i % num_keyword == keyword:
 ```

2022-03-24 03:16 UTC, robin1001 requested changes
please see inline.

2022-03-24 06:33 UTC, robin1001 approved these changes

2022-03-24 06:35 UTC, merged

2022-10-11 09:23 UTC, blessyyyu commented
Okay, I'm extremely grateful for your efforts on reviewing and instruct, and I will finish it on tomorrow morning. Good night every one.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Binbin ***@***.***&gt;; 
发送时间: 2022年3月23日(星期三) 晚上11:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wenet-e2e/wekws] Add calculating long wav frr again (PR #64)





 
@blessyyyu please override score.py and compute_det.py with the new long implementation.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;